apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pt-max-station-web-ha
  namespace: maxstation-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pt-max-station-web
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: maxstation-ingress-web-dev
        target:
          type: Value
          value: 10k
