kind: Service
apiVersion: v1
metadata:
  name: pt-max-station-web-service
  namespace: maxstation-uat
spec:
  type: ClusterIP
  #LoadBalancer
  #NodePort
  #ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: pt-max-station-web
